### ISSUE TITLE
MKB Szépkártya

### ISSUE THREAD

**Issue by pvillanyi** [ofalvai/home-assistant-szep-kartya#6]
Nem lenne kedved átportolni, hogy MKB is lekérdezhető legyen?

**Comment by ofalvai** [comment]
Mivel nincs MKB SZÉP kártyám, ezért nem tudnám lefejleszteni, és főleg karbantartani hosszú távon. Viszont a kód jó kiindulási alap annak, aki hasonlót akar csinálni az MKB rendszerével 😉
